NDefines.NSupply.NODE_STARTING_PENALTY_PER_PROVINCE = 0.1
NDefines.NSupply.NODE_ADDED_PENALTY_PER_PROVINCE = 0.1
NDefines.NSupply.NODE_FLOW_BONUS_PER_RAIL_LEVEL = 1
NDefines.NSupply.VP_TO_SUPPLY_BONUS_CONVERSION = 0.2
NDefines.NSupply.VP_TO_SUPPLY_BASE = 0.6